@port = 5000
@baseUrl = http://localhost:{{port}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2ZTc1ZmY0LTY3YTItNDEzNC1iODRjLWU1ZTgyODA3MWE2YyIsImVtYWlsIjoiZXN0ZWJhbkBnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJBZG9sZm8iLCJsYXN0bmFtZSI6IkFsdmFyZXoiLCJpc19hY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjEtMTEtMDdUMDE6MTY6MjQuMzU4WiIsInVwZGF0ZWRBdCI6IjIwMjEtMTEtMDdUMDE6MTY6MjQuMzU4WiIsImV4cCI6MTYzNjU4MTIwMywiaWF0IjoxNjM2NTgwMzAzfQ.IYL5DURIhAziec1FPmZ8bBp2pjHa8VJ8a2M4xYyLDRo
### POST /auth/signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "email": "esteban@gmail.com",
    "password": "12345678"
}

### POST /users
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "esteban@gmail.com",
    "password": "12345678",
    "firstname": "Adolfo",
    "lastname": "Alvarez"
}

### GET /users
GET {{baseUrl}}/users/me
Authorization: Bearer {{token}}

### PUT /users
PUT {{baseUrl}}/users/813a1a58-38b6-45ea-b653-bea16b95ba44
Content-Type: application/json

{
    "email": "aeap1998@gmail.com"
}

### DELETE /users
DELETE {{baseUrl}}/users/813a1a58-38b6-45ea-b653-bea16b95ba44
